import streamlit as st

from database import db_connection as dbc
from frontend.layout import severity_badge


def _drug_label(d: dict) -> str:
    did = d.get("drug_id") or ""
    nm = d.get("name") or ""
    return f"{nm} ({did})" if nm else did


def show_patient_checker():
    """Patient tool: select 2 drugs and check known interactions, plus AI suggestion (pending doctor review)."""

    dbc.init_db()

    user_id = st.session_state.get("user_id")
    role = (st.session_state.get("role") or "patient").lower()

    st.markdown(
        """
        <div class='glass-card'>
            <h2 style='margin:0'>Check Drug Safety</h2>
            <p style='margin:6px 0 0 0' class='muted'>Select two drugs. The system checks known interactions and can also generate an AI-based suggestion that requires doctor review.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if role not in ("patient", "doctor", "admin"):
        st.warning("Your role is not recognized.")

    drugs = dbc.list_drugs()
    if not drugs:
        st.info("No drugs found in the database.")
        return

    drug_opts = {_drug_label(d): d["drug_id"] for d in drugs}
    labels = list(drug_opts.keys())

    c1, c2 = st.columns(2)
    with c1:
        a_label = st.selectbox("Drug A", labels, key="pc_drug_a")
    with c2:
        b_label = st.selectbox("Drug B", labels, key="pc_drug_b")

    drug_a = drug_opts[a_label]
    drug_b = drug_opts[b_label]

    if drug_a == drug_b:
        st.warning("Please select two different drugs.")
        return

    st.divider()

    # 1) Known interaction (database)
    st.subheader("Known interaction (database)")
    known = dbc.check_interaction_pair(drug_a, drug_b)

    if not known:
        st.info("No known interaction found for this pair.")
    else:
        sev = float(known.get("severity_score", 0.0))
        st.markdown(severity_badge(sev), unsafe_allow_html=True)
        st.write(f"Effect: {known.get('effect_name', '')}")
        if known.get("mechanism"):
            st.caption(known.get("mechanism"))

        # Auto-alert patient if high risk
        if user_id and sev >= 7.0:
            try:
                dbc.create_alert_for_user(
                    user_id=user_id,
                    interaction_id=known.get("interaction_id"),
                    drug1_id=drug_a,
                    drug2_id=drug_b,
                    message=(
                        f"High-risk interaction: {drug_a} + {drug_b} → {known.get('effect_name','')} "
                        f"(Severity {sev:.1f}/10)."
                    ),
                )
                st.success("Alert created for this interaction (check Alerts page).")
            except Exception:
                # de-dupe and DB integrity errors are fine to ignore here
                pass

    st.divider()

    # 2) AI suggestion (pending doctor review)
    st.subheader("AI suggestion (requires doctor review)")
    st.caption(
        "AI suggestions are generated by a simple heuristic for demo purposes and may be incorrect. "
        "A doctor must approve or deny the suggestion."
    )

    if not user_id:
        st.info("Login as a user to store AI suggestions.")
        return

    if st.button("Generate AI suggestion", use_container_width=True, key="pc_gen_ai"):
        try:
            ai = dbc.ai_predict_effect(drug_a, drug_b)
            sid = dbc.store_ai_suggestion(
                user_id,
                drug_a,
                drug_b,
                ai["predicted_effect"],
                ai["severity_score"],
                ai.get("explanation", ""),
            )

            st.success(f"AI suggestion stored as PENDING for doctor review (Suggestion #{sid}).")
            st.markdown(severity_badge(ai["severity_score"]), unsafe_allow_html=True)
            st.write(f"Predicted effect: {ai['predicted_effect']}")
            if ai.get("explanation"):
                st.caption(ai["explanation"])
        except Exception as e:
            st.error(f"AI prediction failed: {e}")
